### ISSUE TITLE
Lesson Does Not Address Testing for Value Exists

### ISSUE THREAD

**Issue by BLK1010** [learn-co-curriculum/ttt-6-position-taken-rb#28] opened 2016-03-20 02:47 UTC
Unless I'm missing something, the lesson content does not seem to contain any information about the final test for the lab which returns "true" if the position in the array already has a value of "X" or "O". I was able to complete the lesson, but I think this might trip some people up.

Thanks.

**Comment by mendelB** [comment] 2016-04-18 22:45
@BLK1010 Thanks for your submission! 
If you take a look at Overview > 3rd column it says: "If the position is free, the method should return false (i.e. "not taken"), otherwise it will return `true`."
(Often a Lab wont be explicit about all the required info and by design will encourage some trial and error)
I'm going to go head and close this Issue. Thanks again!

**Closed as completed by mendelB** 2016-04-18 22:45 UTC
